//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanChecker {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    public sealed partial class SettingsScript : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsScript defaultInstance = ((SettingsScript)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsScript())));
        
        public static SettingsScript Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool accessAdmin {
            get {
                return ((bool)(this["accessAdmin"]));
            }
            set {
                this["accessAdmin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string defaultDataBase {
            get {
                return ((string)(this["defaultDataBase"]));
            }
            set {
                this["defaultDataBase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int prefixLength {
            get {
                return ((int)(this["prefixLength"]));
            }
            set {
                this["prefixLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CustomScriptDataBase {
            get {
                return ((bool)(this["CustomScriptDataBase"]));
            }
            set {
                this["CustomScriptDataBase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CustomScriptDataBasePath {
            get {
                return ((string)(this["CustomScriptDataBasePath"]));
            }
            set {
                this["CustomScriptDataBasePath"] = value;
            }
        }
    }
}
